// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetGroomingAppointmentSystem.Models;

#nullable disable

namespace PetGroomingAppointmentSystem.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20251214112930_AddStatusToService")]
    partial class AddStatusToService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Appointment", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("AdminId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DurationTime")
                        .HasColumnType("int");

                    b.Property<string>("PetId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpecialRequest")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StaffId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PetId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.CustomerRedeemGift", b =>
                {
                    b.Property<string>("CrgId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GiftId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("QuantityRedeemed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RedeemDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CrgId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GiftId");

                    b.ToTable("CustomerRedeemGifts");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Pet", b =>
                {
                    b.Property<string>("PetId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AdminId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Photo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PetId");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.RedeemGift", b =>
                {
                    b.Property<string>("GiftId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AdminId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LoyaltyPointCost")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Photo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("GiftId");

                    b.HasIndex("AdminId");

                    b.ToTable("RedeemGifts");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Service", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AdminId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ServiceId");

                    b.HasIndex("AdminId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.ServiceCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AdminId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.HasIndex("AdminId");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IC")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Photo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Admin", b =>
                {
                    b.HasBaseType("PetGroomingAppointmentSystem.Models.User");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Customer", b =>
                {
                    b.HasBaseType("PetGroomingAppointmentSystem.Models.User");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoyaltyPoint")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Staff", b =>
                {
                    b.HasBaseType("PetGroomingAppointmentSystem.Models.User");

                    b.Property<string>("AdminUserId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ExperienceYear")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("AdminUserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Appointment", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.Admin", "Admin")
                        .WithMany("Appointments")
                        .HasForeignKey("AdminId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Pet");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.CustomerRedeemGift", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.Customer", "Customer")
                        .WithMany("Redeems")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.RedeemGift", "Gift")
                        .WithMany("CustomerRedeemGifts")
                        .HasForeignKey("GiftId");

                    b.Navigation("Customer");

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Pet", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.Admin", "Admin")
                        .WithMany("ManagedPets")
                        .HasForeignKey("AdminId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.User", null)
                        .WithMany("Pets")
                        .HasForeignKey("UserId");

                    b.Navigation("Admin");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.RedeemGift", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.Admin", "Admin")
                        .WithMany("RedeemGifts")
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Service", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.Admin", "Admin")
                        .WithMany("Services")
                        .HasForeignKey("AdminId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Admin");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.ServiceCategory", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.Admin", "Admin")
                        .WithMany("ServiceCategories")
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Admin", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.User", null)
                        .WithOne()
                        .HasForeignKey("PetGroomingAppointmentSystem.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Customer", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.User", null)
                        .WithOne()
                        .HasForeignKey("PetGroomingAppointmentSystem.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Staff", b =>
                {
                    b.HasOne("PetGroomingAppointmentSystem.Models.Admin", "Admin")
                        .WithMany("ManagedStaff")
                        .HasForeignKey("AdminUserId");

                    b.HasOne("PetGroomingAppointmentSystem.Models.User", null)
                        .WithOne()
                        .HasForeignKey("PetGroomingAppointmentSystem.Models.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Pet", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.RedeemGift", b =>
                {
                    b.Navigation("CustomerRedeemGifts");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.User", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Admin", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ManagedPets");

                    b.Navigation("ManagedStaff");

                    b.Navigation("RedeemGifts");

                    b.Navigation("ServiceCategories");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("PetGroomingAppointmentSystem.Models.Customer", b =>
                {
                    b.Navigation("Redeems");
                });
#pragma warning restore 612, 618
        }
    }
}
